### PR TITLE
Migrate Codebase from govendor to Go Modules

### PR DESCRIPTION
**Pull request by livespotty**
Migrated from govendor to Go Modules and reduced dependency

### CODE REVIEW

**Comment by RussellTaylor83** [comment]
I'm a bit late to the party, but is there a reason the repo still hasn't adopted Go Modules?

**Comment by wangzitian0** [comment]
@RussellTaylor83  I think the lastest code has support the go mod and upgrade the deps.
Feel free to pull PR~

**Comment by RussellTaylor83** [comment]
We should probably update the readme to steer people away from Govendor.

**Comment by wangzitian0** [comment]
@RussellTaylor83 Do you have interesting to update the doc and check whether every thing works fine in a new enviroment with a PR?

**Pull request closed without merging**
