### PR TITLE
Made compatible with Go modules

### PR DESCRIPTION
**Pull request by pvillela**
Added go.mod, removed vendors and dependence on github.com/wangzitian0/golang-gin-starter-kit.  All unit tests pass.

### CODE REVIEW

**Review by wangzitian0 — APPROVED** [review]
LGTM! Thanks for the nice change!

**Comment by pvillela** [comment]
My pleasure.  Thank you for writing the nice example code.

Regards,
Paulo

**Comment by wangzitian0** [comment]
@pvillela Do you have time to take a look at the badges at the readme including coverage and CI? Seems it failed after this PR..

**Comment by pvillela** [comment]
I clicked on the badges but I don't have access.  Besides, I'm not familiar
with travis.  Nonetheless, I suspect the problem is due to changes in some
of the dependencies.  I went back to your previous commit on master,
regenerated go.mod, and synced it with vendor.json (go mod vendor).  After
that, I again removed the dependence on the starter-kit repo.  Again, all
unit tests passed.  I have pushed a new PR with this.

**Pull request merged**
